from __future__ import annotations


# 批量配置也保持扁平：引用一个站点配置，然后列出要抓的书籍 ID。
SITE_CONFIG = "jinyong-net"

BOOKS = [
    "old_feihuwaizhuan",
    "feihuwaizhuan",
    "new_feihuwaizhuan",
    "old_xueshanfeihu",
    "xueshanfeihu",
    "new_xueshanfeihu",
    "old_lianchengjue",
    "lianchengjue",
    "new_lianchengjue",
    "old_tianlongbabu",
    "tianlongbabu",
    "new_tianlongbabu",
    "old_shediaoyingxiongzhuan",
    "shediaoyingxiongzhuan",
    "new_shediaoyingxiongzhuan",
    "old_baimaxiaoxifeng",
    "baimaxiaoxifeng",
    "new_baimaxiaoxifeng",
    "old_ludingji",
    "ludingji",
    "new_ludingji",
    "old_xiaoaojianghu",
    "xiaoaojianghu",
    "new_xiaoaojianghu",
    "old_shujianenchoulu",
    "shujianenchoulu",
    "new_shujianenchoulu",
    "old_shendiaoxialv",
    "shendiaoxialv",
    "new_shendiaoxialv",
    "old_xiakexing",
    "xiakexing",
    "new_xiakexing",
    "old_yitiantulongji",
    "yitiantulongji",
    "new_yitiantulongji",
    "old_bixuejian",
    "bixuejian",
    "new_bixuejian",
    "old_yuanyangdao",
    "yuanyangdao",
    "new_yuanyangdao",
    "old_yuenvjian",
    "yuenvjian",
    "new_yuenvjian",
]
